spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:users
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 8082

query:
  select: select * from users